CLASS zcl_pinf_misc2_test DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS:
      constructor.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_PINF_MISC2_TEST IMPLEMENTATION.


  METHOD constructor.
    DATA: lo_class TYPE REF TO zcl_pinf_internal.
    DATA: lo_class2 TYPE REF TO zcl_pinf_test.
  ENDMETHOD.
ENDCLASS.
